Repository sniperfactory-official/sfac-lms-team-a, pull requests merged in 2023-07, with the labels that each got.

#39 Team5 feat/login
  .eslintrc.json
  .husky/commit-msg
  package.json
  public/images/Avatar.png
  public/images/fb.png
  public/images/ln.png
  public/images/login.png
  public/images/logo.png
  public/images/yt.png
  src/app/Provider.tsx
  src/app/community/page.tsx
  src/app/forgotPassword/page.tsx
  src/app/login/page.tsx
  src/app/mypage/page.tsx
  src/app/resetPassword/page.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Navbar.tsx
  src/components/Header/Tab.tsx
  src/components/Loading/Loading.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/RequireAuth/RequireAuth.jsx
  src/components/common/Button.tsx
  src/redux/store.tsx
  src/redux/userSlice.tsx
  src/types/firebase.types.ts
  src/utils/firebase.ts
  tsconfig.json
  yarn.lock
Labels: team10

#42 공통 ModalWrapper 컴포넌트 추가 외 Team8 작업내용 merge
  src/__test__/ModalWrapper.test.tsx
  src/app/assignment/(components)/AssignmentButton.tsx
  src/app/assignment/(components)/Card.tsx
  src/app/assignment/(components)/Feedback.tsx
  src/app/assignment/[assignmentId]/page.tsx
  src/app/assignment/page.tsx
  src/components/ModalWrapper.tsx
  src/hooks/reactQuery/useCreateFeedback.tsx
  src/hooks/reactQuery/useGetFeedbacks.tsx
  src/hooks/reactQuery/useUpdateFeedback.tsx
  src/types/firebase.types.ts
  src/utils/firebase.ts
  src/utils/getTime.ts
  tsconfig.json
Labels: team8

#46 Refactor: 코드리뷰 수정 사항
  src/components/Footer/Footer.tsx
  src/components/Header/Navbar.tsx
Labels: team10

#47 Team10 refactor/auth
  src/components/Auth/sign.tsx
  src/components/Header/Navbar.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/index.tsx
  src/hooks/reactQuery/index.tsx
  src/hooks/reactQuery/login/useLoginQuery.ts
  src/hooks/reactQuery/logout/useLogoutQuery.ts
  src/hooks/reactQuery/reset/useGetUserinfoQuery.ts
  src/redux/userSlice.tsx
  src/utils/firebase.ts
Labels: team10

#49 Team4 feat 강의장 뼈대 만들기
  src/app/classroom/(components)/Button.tsx
  src/app/classroom/layout.tsx
  src/app/classroom/page.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Footer.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Note.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/app/lectureHall/__test__/LectureHader.test.tsx
  src/app/lectureHall/__test__/TestReactQueryClientProvider.tsx
  src/app/lectureHall/layout.tsx
  src/app/lectureHall/page.tsx
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureInfoQuery.ts
  src/utils/firebase.ts
  src/utils/getTime.ts
  src/utils/timestampToDate.ts
Labels: team4

#50 Feat: Drag & Drop 기능 구현
  package.json
  public/images/clip.svg
  src/components/upload/FileItem.tsx
  src/components/upload/Upload.tsx
  yarn.lock
Labels: enhancement, team4

#51 Team8 fix/feedback
  public/images/logo.svg
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackForm.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/app/assignment/(components)/Feedback.tsx
  src/app/assignment/page.tsx
  src/hooks/reactQuery/useCreateFeedback.tsx
  src/hooks/reactQuery/useDeleteFeedback.tsx
  src/hooks/reactQuery/useGetFeedbacks.tsx
  src/hooks/reactQuery/useUpdateFeedback.tsx
Labels: team8

#54 Refactor: 공통 Sidebar 컴포넌트 리팩토링
  src/app/classroom/(components)/Button.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Footer.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/components/Sidebar.tsx
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
Labels: team8, team4

#53 Fix: 공통 컴포넌트 및 auth 기능 구현 풀리퀘스트
  .eslintrc.json
  .husky/commit-msg
  package.json
  public/images/avatar.svg
  public/images/facebookLogo.svg
  public/images/instagramLogo.svg
  public/images/login.svg
  public/images/logo.svg
  public/images/youtubeLogo.svg
  src/app/Provider.tsx
  src/app/community/page.tsx
  src/app/forgotPassword/page.tsx
  src/app/mypage/page.tsx
  src/app/page.tsx
  src/app/resetPassword/page.tsx
  src/components/Auth/Auth.tsx
  src/components/Auth/sign.tsx
  src/components/Footer/Footer.tsx
  src/components/Header/Navbar.tsx
  src/components/Header/Tab.tsx
  src/components/Loading/Loading.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/components/common/Button.tsx
  src/components/index.tsx
  src/components/password/ForgotPassword.tsx
  src/components/password/ResetPassword.tsx
  src/hooks/reactQuery/index.tsx
  src/hooks/reactQuery/login/useLoginQuery.ts
  src/hooks/reactQuery/logout/useLogoutQuery.ts
  src/hooks/reactQuery/navbar/useGetLectureQuery.ts
  src/hooks/reactQuery/navbar/useGetUserQuery.ts
  src/hooks/reactQuery/reset/useGetUserinfoQuery.ts
  src/redux/store.tsx
  src/redux/userSlice.tsx
  src/utils/firebase.ts
  yarn.lock
Labels: enhancement, team10

#57 Feat:
  package.json
  public/images/inputAvatar.svg
  public/images/inputMessage.svg
  public/images/submitButton.svg
  src/app/community/page.tsx
  src/components/Community/Aside/Aside.tsx
  src/components/Community/Aside/Button.tsx
  src/components/Community/Inputbar.tsx
  src/components/Community/Layout.tsx
  src/components/Community/PostForm.tsx
  src/components/Community/SelectMenu.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/ModalWrapper.tsx
  src/components/common/Button.tsx
  src/constants/category.ts
  src/utils/firebase.ts
  yarn.lock
Labels: enhancement, team10

#55 Team4
  package.json
  public/images/clip.svg
  src/app/classroom/(components)/Button.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/layout.tsx
  src/app/classroom/page.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Footer.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Note.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/app/lectureHall/__test__/LectureHader.test.tsx
  src/app/lectureHall/__test__/TestReactQueryClientProvider.tsx
  src/app/lectureHall/layout.tsx
  src/app/lectureHall/page.tsx
  src/components/Sidebar.tsx
  src/components/upload/FileItem.tsx
  src/components/upload/Upload.tsx
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureInfoQuery.ts
  src/utils/timestampToDate.ts
  yarn.lock
Labels: team4

#59 Feat: 커뮤니티 게시글 상세보기 모달 기능 구현
  next.config.js
  public/images/화살표.svg
  src/components/CommunityModal/CommunityModal.tsx
  src/components/CommunityModal/ImageModal.tsx
  src/components/Header/Navbar.tsx
  src/components/common/PostButton.tsx
  src/components/password/ForgotPassword.tsx
  src/components/password/ResetPassword.tsx
  src/hooks/reactQuery/comment/useComment.ts
  src/hooks/reactQuery/comment/useCreateComment.ts
  src/hooks/reactQuery/comment/useDeleteComment.ts
  src/hooks/reactQuery/comment/useNestedComment.ts
  src/hooks/reactQuery/comment/useUpdateComment.ts
  src/hooks/reactQuery/community/useGetPostImage.tsx
  src/hooks/reactQuery/login/useFindPassword.ts
  src/hooks/reactQuery/navbar/useGetUserQuery.ts
  src/hooks/reactQuery/reset/useGetUserinfoQuery.ts
  src/hooks/reactQuery/useGetPostQuery.tsx
  src/hooks/reactQuery/useGetSelectedPost.tsx
  src/utils/firebase.ts
Labels: team10

#60 Team8 fix/feedback
  public/images/logo.svg
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCreate.tsx
  src/app/assignment/(components)/(feedback)/FeedbackForm.tsx
  src/app/assignment/(components)/(feedback)/FeedbackUpdate.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/assignment/(components)/Card.tsx
  src/hooks/reactQuery/useUpdateFeedback.tsx
  src/types/feedback.types.ts
  src/types/firebase.types.ts
Labels: team8
