Repository sniperfactory-official/sfac-lms-team-a, pull requests merged in 2023-08, with the labels that each got.

#64 Team4 feat 강의장 커뮤니티 완성하기
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentModify.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/(communityArea)/CommunityItem.tsx
  src/app/lectureHall/(components)/(communityArea)/ReplyItem.tsx
  src/app/lectureHall/(components)/(communityArea)/communityItemList.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/app/lectureHall/page.tsx
  src/hooks/reactQuery/lecture/useDeleteLectureComment.ts
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureInfoQuery.ts
  src/hooks/reactQuery/lecture/useLectureCommentMutation.ts
  src/hooks/reactQuery/lecture/useModifyLectureComment.ts
  src/utils/firebase.ts
  yarn.lock
Labels: team4

#62 Fix: 커뮤니티 모달창 컴포넌트 작업 및 이미지 첨부 공통 컴포넌트 작업
  public/images/cancel.svg
  public/images/upload.svg
  src/components/Community/PostForm.tsx
  src/components/Community/SelectMenu.tsx
  src/components/Header/Navbar.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/common/Button.tsx
  src/components/common/ImageUploader.tsx
  src/hooks/reactQuery/login/useLoginMutation.ts
  src/hooks/reactQuery/logout/useLogoutMutation.ts
  src/utils/sign.tsx
Labels: enhancement, team10

#69 Team8 작업내용 merge
  public/images/close.svg
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCreate.tsx
  src/app/assignment/(components)/(feedback)/FeedbackForm.tsx
  src/app/assignment/(components)/(feedback)/FeedbackUpdate.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/app/assignment/(components)/Card.tsx
  src/app/assignment/(components)/Feedback.tsx
  src/app/assignment/page.tsx
  src/components/ModalWrapper.tsx
  src/example/ModalExample.tsx
  src/hooks/reactQuery/useCreateFeedback.tsx
  src/hooks/reactQuery/useDeleteFeedback.tsx
  src/hooks/reactQuery/useGetFeedbacks.tsx
  src/hooks/reactQuery/useUpdateFeedback.tsx
  src/types/feedback.types.ts
  src/types/firebase.types.ts
Labels: team8

#56 Feat: 강의리스트 불러오기
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/page.tsx
  src/hooks/reactQuery/lecture/useGetAllLectureListQuery.ts
  src/hooks/reactQuery/lecture/useGetCoursesInfoQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureListQuery.ts
Labels: team4

#74 Fix: upload
  src/components/upload/FileItem.tsx
  src/components/upload/Upload.tsx
Labels: team4

#72 Refactor: 공통 Sidebar 컴포넌트 리팩토링
  src/app/assignment/(components)/Sidebar.example.tsx
  src/app/classroom/(components)/Course.example.tsx
  src/components/Sidebar.tsx
Labels: team8, team4

#82 Feat: Aside, CommunityList
  public/images/noPostingMessage.svg
  src/app/community/page.tsx
  src/components/Community/Aside/Aside.tsx
  src/components/Community/Aside/Button.tsx
  src/components/Community/CommunityCard.tsx
  src/components/Community/CommunityList.tsx
  src/components/common/ImageUploader.tsx
  src/hooks/reactQuery/comment/useCommentCount.tsx
  src/hooks/reactQuery/community/useFetchThumbnail.tsx
  src/hooks/reactQuery/useGetSelectedPost.tsx
  tailwind.config.js
Labels: team10

#84 Feat: 커뮤니티 글 작성 기능 및 이미지 첨부 공통 컴포넌트 구현
  package.json
  public/images/clip.svg
  public/images/close.svg
  public/images/logo.svg
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCreate.tsx
  src/app/assignment/(components)/(feedback)/FeedbackForm.tsx
  src/app/assignment/(components)/(feedback)/FeedbackUpdate.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/app/assignment/(components)/Card.tsx
  src/app/assignment/(components)/Feedback.tsx
  src/app/assignment/page.tsx
  src/app/classroom/(components)/Button.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/layout.tsx
  src/app/classroom/page.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Footer.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Note.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/app/lectureHall/__test__/LectureHader.test.tsx
  src/app/lectureHall/__test__/TestReactQueryClientProvider.tsx
  src/app/lectureHall/layout.tsx
  src/app/lectureHall/page.tsx
  src/app/page.tsx
  src/components/Auth/Auth.tsx
  src/components/Community/Layout.tsx
  src/components/Community/PostForm.tsx
  src/components/Header/Navbar.tsx
  src/components/Header/Tab.tsx
  src/components/LoginForm/LoginForm.tsx
  src/components/ModalWrapper.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/components/Sidebar.tsx
  src/components/common/ImageUploader.tsx
  src/components/upload/FileItem.tsx
  src/components/upload/Upload.tsx
  src/example/ModalExample.tsx
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureInfoQuery.ts
  src/hooks/reactQuery/login/useLoginMutation.ts
  src/hooks/reactQuery/post/useCreatePostMutation.tsx
  src/hooks/reactQuery/useCreateFeedback.tsx
  src/hooks/reactQuery/useDeleteFeedback.tsx
  src/hooks/reactQuery/useGetFeedbacks.tsx
  src/hooks/reactQuery/useUpdateFeedback.tsx
  src/types/feedback.types.ts
  src/types/firebase.types.ts
  src/utils/imageCompress.ts
  src/utils/timestampToDate.ts
  src/utils/uploadStorageImages.ts
  yarn.lock
Labels: enhancement, team10

#87 Team4 드래그 앤 드롭, 사이드 바, 강의장 커뮤니티
  next.config.js
  package.json
  public/images/Arrow.svg
  public/images/replyCommentArrow.svg
  src/app/assignment/(components)/Sidebar.example.tsx
  src/app/classroom/(components)/Course.example.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/page.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Note.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentContent.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentModify.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/(communityArea)/CommunityItem.tsx
  src/app/lectureHall/(components)/(communityArea)/ReplyItem.tsx
  src/app/lectureHall/(components)/(communityArea)/communityItemList.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/app/lectureHall/page.tsx
  src/components/Header/Navbar.tsx
  src/components/Sidebar.tsx
  src/components/upload/FileItem.tsx
  src/components/upload/Upload.tsx
  src/hooks/reactQuery/lecture/useDeleteLectureComment.ts
  src/hooks/reactQuery/lecture/useGetAllLectureListQuery.ts
  src/hooks/reactQuery/lecture/useGetCoursesInfoQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureInfoQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureListQuery.ts
  src/hooks/reactQuery/lecture/useLectureCommentMutation.ts
  src/hooks/reactQuery/lecture/useModifyLectureComment.ts
  src/utils/firebase.ts
  tailwind.config.js
  yarn.lock
Labels: team4, Pull requests

#92 Fix: store 저장 정보 변경 / 로그인 로직 / PostForm 리팩토링 풀리퀘스트
  src/components/Community/PostForm.tsx
  src/components/Header/Navbar.tsx
  src/components/common/ImageUploader.tsx
  src/hooks/reactQuery/login/useLoginMutation.ts
  src/hooks/reactQuery/post/useCreatePostMutation.ts
  src/redux/store.tsx
  src/redux/userSlice.tsx
  src/types/firebase.types.ts
  src/utils/sign.tsx
Labels: enhancement, team10

#95 Update: ModalWrapper props 추가
  src/components/ModalWrapper.tsx
Labels: enhancement

#90 Team8 feat/assignment submit
  next.config.js
  package.json
  public/images/Arrow.svg
  public/images/replyCommentArrow.svg
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignment.tsx
  src/app/assignment/(components)/Sidebar.example.tsx
  src/app/classroom/(components)/Course.example.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/page.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Note.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentContent.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentModify.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/(communityArea)/CommunityItem.tsx
  src/app/lectureHall/(components)/(communityArea)/ReplyItem.tsx
  src/app/lectureHall/(components)/(communityArea)/communityItemList.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/app/lectureHall/page.tsx
  src/components/Header/Navbar.tsx
  src/components/ModalWrapper.tsx
  src/components/Sidebar.tsx
  src/components/upload/FileItem.tsx
  src/components/upload/Upload.tsx
  src/hooks/reactQuery/lecture/useDeleteLectureComment.ts
  src/hooks/reactQuery/lecture/useGetAllLectureListQuery.ts
  src/hooks/reactQuery/lecture/useGetCoursesInfoQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureCommentQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureInfoQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureListQuery.ts
  src/hooks/reactQuery/lecture/useLectureCommentMutation.ts
  src/hooks/reactQuery/lecture/useModifyLectureComment.ts
  src/hooks/reactQuery/submittedAssignment/useGetSubmittedAssignment.ts
  src/utils/firebase.ts
  tailwind.config.js
  yarn.lock
Labels: team8

#91 Team8 feat/feedback
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackButton.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCreate.tsx
  src/app/assignment/(components)/(feedback)/FeedbackForm.tsx
  src/app/assignment/(components)/(feedback)/FeedbackTextArea.tsx
  src/app/assignment/(components)/(feedback)/FeedbackUpdate.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/hooks/common/useReturnToUserRef.tsx
  src/hooks/reactQuery/feedback/useCreateFeedback.tsx
  src/hooks/reactQuery/feedback/useDeleteFeedback.tsx
  src/hooks/reactQuery/feedback/useFeedbackActions.tsx
  src/hooks/reactQuery/feedback/useGetFeedbacks.tsx
  src/hooks/reactQuery/feedback/useMutateFeedback.tsx
  src/hooks/reactQuery/feedback/useUpdateFeedback.tsx
  src/types/feedback.types.ts
  yarn.lock
Labels: team8

#100 Fix: 커뮤니티 레이아웃 변경
  src/app/community/page.tsx
  src/components/Community/CommunityList.tsx
  src/components/Community/Inputbar.tsx
  src/components/Community/Layout.tsx
  src/components/Community/SelectMenu.tsx
  src/constants/category.ts
  src/hooks/reactQuery/post/useCreatePostMutation.tsx
Labels: enhancement, team10

#103 Team4 feat 사이드바
  public/images/close.svg
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCreate.tsx
  src/app/assignment/(components)/(feedback)/FeedbackForm.tsx
  src/app/assignment/(components)/(feedback)/FeedbackUpdate.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/app/assignment/(components)/Card.tsx
  src/app/assignment/(components)/Feedback.tsx
  src/app/assignment/page.tsx
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/CourseSection.tsx
  src/app/classroom/page.tsx
  src/components/ModalWrapper.tsx
  src/components/Sidebar.tsx
  src/example/ModalExample.tsx
  src/hooks/reactQuery/lecture/useGetAllLectureListQuery.ts
  src/hooks/reactQuery/lecture/useGetCoursesInfoQuery.ts
  src/hooks/reactQuery/useCreateFeedback.tsx
  src/hooks/reactQuery/useDeleteFeedback.tsx
  src/hooks/reactQuery/useGetFeedbacks.tsx
  src/hooks/reactQuery/useUpdateFeedback.tsx
  src/types/feedback.types.ts
  src/types/firebase.types.ts
Labels: enhancement, team4

#102 Feat: 제출된 과제 파일 다운로드 기능 추가
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignment.tsx
  src/utils/downloadAssignmentFile.ts
Labels: team8

#105 Fix: 커뮤니티 페이지 글 제출 시 firebase에 등록 로직 수정 (userId 추가)
  src/app/community/page.tsx
  src/components/Community/CommunityList.tsx
  src/components/Community/PostForm.tsx
  src/constants/category.ts
  src/hooks/reactQuery/post/useCreatePostMutation.ts
  src/hooks/reactQuery/post/useCreatePostMutation.tsx
  src/hooks/reactQuery/useGetSelectedPost.tsx
Labels: enhancement, team10

#106 Team4 feat 섹션생성하기
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/components/ModalWrapper.tsx
  src/hooks/reactQuery/lecture/useCreateCourse.ts
  src/hooks/reactQuery/lecture/useDeleteCourse.ts
Labels: enhancement, team4

#99 Feat: 강의 생성하기
  package.json
  public/images/arrow.svg
  public/images/link.svg
  public/images/note.svg
  public/images/video.svg
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/CreateLectureMethod.tsx
  src/app/classroom/(components)/LectureButton.tsx
  src/app/classroom/(components)/LectureLink.tsx
  src/app/classroom/(components)/LectureNote.tsx
  src/app/classroom/(components)/LecturePrivate.tsx
  src/app/classroom/(components)/LectureTimestamp.tsx
  src/app/classroom/(components)/LectureTitle.tsx
  src/app/classroom/(components)/LectureVideo.tsx
  src/components/upload/Upload.tsx
  src/hooks/reactQuery/lecture/useCreateLecture.ts
  src/utils/uploadFileToStorage.ts
  yarn.lock
Labels: enhancement, team4

#109 Fix: ModalWrapper 수정에 따른 props, style 수정
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/CreateLectureMethod.tsx
  src/app/classroom/(components)/LectureNote.tsx
Labels: team4, Pull requests

#112 Team4 feat 사이드바 강의장 연결
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/CourseSection.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/page.tsx
Labels: enhancement, team4

#116 Update: 팀4 작업내용 통합
  public/images/backPage.svg
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/CourseSection.tsx
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/(components)/Sidebar.tsx
  src/app/classroom/ClassRoomWrapper.tsx
  src/app/classroom/page.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(LetcureArea)/externalLink.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentModify.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(mainLectureHall)/MainContent.tsx
  src/components/Header/Navbar.tsx
  src/components/ModalWrapper.tsx
  src/hooks/reactQuery/lecture/useCreateLecture.ts
  src/hooks/reactQuery/lecture/useDeleteCourse.ts
  src/hooks/reactQuery/lecture/useGetAllLectureListQuery.ts
  src/hooks/reactQuery/lecture/useGetLectureListQuery.ts
  src/redux/lectureSlice.ts
Labels: team4, Pull requests

#120 Feat: 커뮤니티 페이지 글 수정 기능 구현
  src/components/Community/CommunityCard.tsx
  src/components/Community/CommunityList.tsx
  src/components/Community/Inputbar.tsx
  src/components/Community/Layout.tsx
  src/components/Community/PostForm/PostForm.tsx
  src/components/Community/PostForm/SelectMenu.tsx
  src/components/CommunityModal/CommunityModal.tsx
  src/components/ModalWrapper.tsx
  src/components/common/ImageUploader.tsx
  src/constants/a.ts
  src/hooks/reactQuery/comment/useCommentCount.ts
  src/hooks/reactQuery/community/useCreatePostMutation.ts
  src/hooks/reactQuery/community/useDeletePost.ts
  src/hooks/reactQuery/community/useFetchThumbnail.ts
  src/hooks/reactQuery/community/useGetPostImage.ts
  src/hooks/reactQuery/community/useGetProfileImage.ts
  src/hooks/reactQuery/community/useUpdatePostMutation.ts
  src/hooks/reactQuery/useGetSelectedCategory.ts
  src/hooks/reactQuery/useGetSelectedPost.ts
  src/redux/postSlice.ts
  src/redux/store.ts
  src/redux/userSlice.ts
  src/types.d.ts
  src/types/index.tsx
  src/utils/imageCompress.ts
  src/utils/index.tsx
  src/utils/sign.ts
  src/utils/uploadStorageImages.ts
Labels: enhancement, team10

#124 Team8 피드백 prefetch 기능 추가
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCardSkeleton.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/hooks/reactQuery/feedback/useGetFeedbacks.tsx
  src/hooks/reactQuery/feedback/useMutateFeedback.tsx
Labels: team8

#130 Fix: community update post
  src/components/Community/Aside/Aside.tsx
  src/components/Community/CommunityCard.tsx
  src/components/Community/CommunityList.tsx
  src/components/Community/Layout.tsx
  src/components/Community/PostForm/PostForm.tsx
  src/components/Community/PostForm/PostTags.tsx
  src/components/Community/PostForm/SelectMenu.tsx
  src/components/CommunityModal/CommunityModal.tsx
  src/components/common/Button.tsx
  src/components/common/ImageUploader.tsx
  src/hooks/reactQuery/comment/useCreateComment.ts
  src/utils/deleteStorageImages.ts
  src/utils/imageCompress.ts
  src/utils/uploadStorageImages.ts
Labels: enhancement, team10

#131 Feat: 리스트페이지 기능개발, DnDWrapper order값기능추가
  public/images/Vector.svg
  src/app/assignment/(components)/(assignmentlist)/AssignmentCard.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentListBox.tsx
  src/app/assignment/(components)/AssignmentSidebar.tsx
  src/app/assignment/page.tsx
  src/app/assignment/testside/page.tsx
  src/components/DnDWrapper.tsx
  src/components/Sidebar.tsx
  src/hooks/common/useHandleListCheck.tsx
  src/hooks/reactQuery/assignment/useDeleteAssignments.tsx
  src/hooks/reactQuery/assignment/useGetAssignments.tsx
  src/hooks/reactQuery/assignment/useUpdateAssignmentOrder.tsx
Labels: team8

#139 Team10 : 마이페이지 - 과제 제출 Reminder
  src/app/mypage/page.tsx
  src/components/Mypage/Reminder.tsx
  src/hooks/reactQuery/mypage/useGetAssignmentsByUser.tsx
Labels: team10

#145 Team4 feat 강의실 강의리스트 개별 삭제
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/CourseSection.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/components/Sidebar.tsx
  src/hooks/reactQuery/lecture/useDeleteLecture.ts
  src/hooks/reactQuery/lecture/useUpdateCourseTitle.ts
  src/hooks/reactQuery/lecture/useUpdateLectureOrder.ts
Labels: enhancement, team4

#147 Feat: 강의 수정하기 기능 구현
  public/images/Arrow.svg
  public/images/lectureArrow.svg
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/LectureLink.tsx
  src/app/classroom/(components)/LectureNote.tsx
  src/app/classroom/(components)/LecturePrivate.tsx
  src/app/classroom/(components)/LectureTimestamp.tsx
  src/app/classroom/(components)/LectureTitle.tsx
  src/app/classroom/(components)/LectureVideo.tsx
  src/app/classroom/(components)/UpdateLecture.tsx
  src/hooks/reactQuery/lecture/useCreateLecture.ts
  src/hooks/reactQuery/lecture/useGetLectureInfo.ts
  src/hooks/reactQuery/lecture/useUpdateLecture.ts
  src/utils/deleteFileFromStorage.ts
  src/utils/getFileNameFromURL.ts
Labels: enhancement, team4

#151 Fix: Redirect 오류 해결
  src/components/RequireAuth/RequireAuth.tsx
Labels: bug, team10

#159 Team10 feat/mypage error
  src/app/mypage/page.tsx
  src/components/Community/CommunityCard.tsx
  src/components/Community/Inputbar.tsx
  src/components/Community/PostForm/PostForm.tsx
  src/components/CommunityModal/CommentCard.tsx
  src/components/CommunityModal/CommentInput.tsx
  src/components/CommunityModal/PostCard.tsx
  src/components/Header/Navbar.tsx
  src/hooks/reactQuery/useGetProgressQuery.tsx
Labels: team10

#160 Team4 feat 사이드바 스타일링 수정
  public/images/noLectureItem.svg
  public/images/privateThumbnail.svg
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/components/RequireAuth/RequireAuth.tsx
  src/components/Sidebar.tsx
Labels: team4

#163 Style: 디자인 시스템 팀 DateSelector 적용
  package-lock.json
  package.json
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/LectureDateSelector.tsx
  src/app/classroom/(components)/LectureTimestamp.tsx
  src/app/classroom/(components)/LectureTitle.tsx
  src/app/classroom/(components)/UpdateLecture.tsx
  src/app/layout.tsx
  yarn.lock
Labels: enhancement, team4

#165 Team8 fix/feedback
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackButton.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackTextArea.tsx
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/app/assignment/(components)/SubmittedAssignmentDetail.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/SubmitAssignmentCard.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/SubmittedAssignmentList.tsx
  src/types/feedback.types.ts
Labels: team8

#166 Feat: 과제 롤분기처리
  src/app/assignment/(components)/(assignmentlist)/AssignmentCard.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentListBox.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentRoleCheck.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentSidebarButtons.tsx
  src/app/assignment/(components)/AssignmentSidebar.tsx
  src/hooks/reactQuery/assignment/useGetCurrentStudentSubmittedAssignments.tsx
Labels: team8

#171 Team8 refactor/feedback
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackTextArea.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
Labels: team8

#173 Fix: 프로필 사진 에러
  src/app/mypage/page.tsx
  src/hooks/reactQuery/community/useUpdateProfileImage.ts
  src/hooks/reactQuery/mypage/useProfileImage.ts
Labels: bug, team10

#175 Team4 강의장 디자인 작업
  package.json
  public/images/blueAdd.svg
  src/app/assignment/(components)/(assignmentCreateModal)/DatePicker.tsx
  src/app/assignment/(components)/(assignmentCreateModal)/Modal.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentCard.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentListBox.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentRoleCheck.tsx
  src/app/assignment/(components)/(assignmentlist)/AssignmentSidebarButtons.tsx
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackButton.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackTextArea.tsx
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
  src/app/assignment/(components)/AssignmentDetail.tsx
  src/app/assignment/(components)/AssignmentSidebar.tsx
  src/app/assignment/(components)/Sidebar.example.tsx
  src/app/assignment/(components)/SubmittedAssignmentDetail.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/Main.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/SubmitAssignmentCard.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/SubmittedAssignmentList.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Footer.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentContent.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentModify.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/(communityArea)/CommunityItem.tsx
  src/app/lectureHall/(components)/(communityArea)/ReplyItem.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/hooks/reactQuery/assignment/useGetCurrentStudentSubmittedAssignments.tsx
  src/types/feedback.types.ts
  src/types/firebase.types.ts
  yarn.lock
Labels: team4, Pull requests

#177 Fix: 강의 수정하기 에러 수정
  package-lock.json
  package.json
  public/images/lectureArrow.svg
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/CreateLectureMethod.tsx
  src/app/classroom/(components)/LectureVideo.tsx
  src/app/classroom/(components)/UpdateLecture.tsx
  src/hooks/reactQuery/lecture/useGetLectureInfo.ts
  yarn.lock
Labels: bug, team4

#181 Fix: LectureVideo 에러 수정
  src/app/classroom/(components)/LectureVideo.tsx
Labels: bug, team4

#182 Team4 feat 강의실 스타일수정
  public/images/lecturethumbnail.svg
  public/images/sectionAdd.svg
  public/images/sectionEdit.svg
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/CourseSection.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/ClassRoomWrapper.tsx
  src/components/Sidebar.tsx
  tailwind.config.js
Labels: enhancement, team4

#178 Team8 fix 과제 삭제 로직 수정 및 생성order값변경
  src/app/assignment/(components)/AssignmentSidebar.tsx
  src/hooks/reactQuery/assignment/useCreateAssignment .tsx
  src/hooks/reactQuery/assignment/useDeleteAssignments.tsx
Labels: team8

#190 Team8 refactor/feedback
  package.json
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackButton.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/layout.tsx
  src/components/common/Toast.tsx
  src/hooks/reactQuery/feedback/useMutateFeedback.tsx
  src/types/feedback.types.ts
  tailwind.config.js
Labels: team8

#191 Feat: 제출된 과제 삭제 기능 추가
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
  src/app/assignment/(components)/AssignmentFileSubmitModal.tsx
  src/app/assignment/(components)/AssignmentLinkSubmitModal.tsx
  src/app/assignment/(components)/StudentAssignmentSubmitCard.tsx
  src/app/assignment/(components)/SubmittedAssignmentDetail.tsx
  src/hooks/reactQuery/submittedAssignment/useDeleteSubmittedAssignment.ts
Labels: team8

#185 Team4
  package-lock.json
  package.json
  public/images/arrow.svg
  public/images/lectureArrow.svg
  public/images/lecturethumbnail.svg
  public/images/noLectureItem.svg
  public/images/privateThumbnail.svg
  public/images/sectionAdd.svg
  public/images/sectionEdit.svg
  src/app/classroom/(components)/ClassroomSidebar.tsx
  src/app/classroom/(components)/CourseSection.tsx
  src/app/classroom/(components)/CreateLecture.tsx
  src/app/classroom/(components)/CreateLectureMethod.tsx
  src/app/classroom/(components)/LectureDateSelector.tsx
  src/app/classroom/(components)/LectureItem.tsx
  src/app/classroom/(components)/LectureList.tsx
  src/app/classroom/(components)/LectureTimestamp.tsx
  src/app/classroom/(components)/LectureTitle.tsx
  src/app/classroom/(components)/LectureVideo.tsx
  src/app/classroom/(components)/UpdateLecture.tsx
  src/app/classroom/ClassRoomWrapper.tsx
  src/app/layout.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Footer.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureContent.tsx
  src/app/lectureHall/(components)/(LetcureArea)/LectureTimer.tsx
  src/app/lectureHall/(components)/(LetcureArea)/Video.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentContent.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentInput.tsx
  src/app/lectureHall/(components)/(communityArea)/CommentModify.tsx
  src/app/lectureHall/(components)/(communityArea)/Community.tsx
  src/app/lectureHall/(components)/(communityArea)/CommunityItem.tsx
  src/app/lectureHall/(components)/(communityArea)/ReplyItem.tsx
  src/app/lectureHall/(components)/(communityArea)/communityItemList.tsx
  src/app/lectureHall/(components)/Header.tsx
  src/app/lectureHall/(components)/Wrapper.tsx
  src/components/Sidebar.tsx
  src/hooks/reactQuery/lecture/useGetLectureInfo.ts
  src/hooks/reactQuery/lecture/useGetVideoProgress.ts
  src/hooks/reactQuery/lecture/useProgressMutation.ts
  src/utils/timeToSecnods.ts
  tailwind.config.js
  yarn.lock
Labels: team4, Pull requests

#193 Update: 제출된 과제 파일 item 클릭 시 pdf url로 이동하도록 기능 수정
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
  src/app/assignment/(components)/StudentAssignmentSubmitCard.tsx
  src/components/upload/Upload.tsx
  src/utils/downloadAssignmentFile.ts
Labels: team8

#195 Refactor: useDeleteSubmittedAssignment hook 리팩토링
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
  src/hooks/reactQuery/submittedAssignment/useDeleteSubmittedAssignment.ts
Labels: team8

#197 Team8
  src/app/assignment/(components)/(assignmentCreateModal)/DatePicker.tsx
  src/app/assignment/(components)/(assignmentCreateModal)/FileUploader.tsx
  src/app/assignment/(components)/(assignmentCreateModal)/Modal.tsx
  src/app/assignment/(components)/(feedback)/Feedback.tsx
  src/app/assignment/(components)/(feedback)/FeedbackButton.tsx
  src/app/assignment/(components)/(feedback)/FeedbackCard.tsx
  src/app/assignment/(components)/(feedback)/FeedbackTextArea.tsx
  src/app/assignment/(components)/(feedback)/VerificationModal.tsx
  src/app/assignment/(components)/(submittedAssignment)/SubmittedAssignmentContent.tsx
  src/app/assignment/(components)/AssignmentFileSubmitModal.tsx
  src/app/assignment/(components)/AssignmentLinkSubmitModal.tsx
  src/app/assignment/(components)/AssignmentSidebar.tsx
  src/app/assignment/(components)/StudentAssignmentSubmitCard.tsx
  src/app/assignment/(components)/SubmittedAssignmentDetail.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/Detail.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/Main.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/SubmitAssignmentCard.tsx
  src/app/assignment/[assignmentId]/(assignmentDetail)/SubmittedAssignmentList.tsx
  src/app/assignment/layout.tsx
  src/app/layout.tsx
  src/components/Sidebar.tsx
  src/components/common/Toast.tsx
  src/components/upload/Upload.tsx
  src/hooks/common/useModal.tsx
  src/hooks/reactQuery/assignment/useCreateAssignment .tsx
  src/hooks/reactQuery/assignment/useDeleteAssignments.tsx
  src/hooks/reactQuery/assignment/useGetDetailAssignment.tsx
  src/hooks/reactQuery/assignment/useUpdateAssignment .tsx
  src/hooks/reactQuery/feedback/useMutateFeedback.tsx
  src/hooks/reactQuery/submittedAssignment/useDeleteSubmittedAssignment.ts
  src/hooks/reactQuery/submittedAssignment/useGetSubmittedAssignementId.ts
  src/hooks/reactQuery/submittedAssignment/useGetSubmittedAssignment.ts
  src/types/feedback.types.ts
  src/utils/downloadAssignmentFile.ts
  tailwind.config.js
  yarn.lock
Labels: team8

#202 Fix: 강의장 오타 수정
  src/app/classroom/(components)/LectureItem.tsx
Labels: team8, team4, team10, Pull requests

#203 Fix: 마이페이지 제출과제 목록 링크 수정
  src/app/mypage/(components)/AssignmentsDetailModal.tsx
  src/app/mypage/(components)/Category.tsx
Labels: bug, enhancement, team10
